# site settings
title: Hiro
subtitle: by HTML5 UP
email: guilhermehiroshifujii@gmail.com
description: Portfólio de projetos </br> Desenhista Projetista Mecânico evoluindo para a Robótica | Desenvolvedor de Soluções de Automação
baseurl: "" # "/forty-jekyll-theme" - the subpath of your site, e.g. /blog
url: https://guilhermehiroshifujii.github.io # the base hostname & protocol for your site
author: Guilherme Hiroshi
# street_address: 1234 Somewhere Road
# city: Mogi das cruzes
# state: SP
# zip_code: 55555
# country: Brasil
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/guilhermehiroshifujii
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/guilherme-hiroshi-fujii
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
